[package]

name = "collision"
version = "0.19.0"
authors = ["Brendan Zabarauskas <bjzaba@yahoo.com.au>",
        "Brian Heylin",
        "Colin Sherratt",
        "Dzmitry Malyshau",
        "Erick Tryzelaar",
        "Ilya Bogdanov",
        "Luqman Aden",
        "Maik Klein",
        "Mikko Perttunen",
        "Simon Rönnberg",
        "Pierre Krieger",
        "Tomasz Stachowiak",
        "Zeke Foppa"
]
license = "Apache-2.0"
description = "A collision extension to cgmath"
edition = "2018"

documentation = "https://docs.rs/collision"
homepage = "https://github.com/rustgd/collision-rs"
repository = "https://github.com/rustgd/collision-rs"
readme = "README.md"

keywords = ["gamedev", "cgmath", "collision"]

[lib]
name = "collision"

[dependencies]
num = "0.2"
rand = "0.4"
approx = "0.1"
cgmath = "0.16"
mint = "0.5"
serde = { version = "1.0", optional = true, features = ["derive"] }
bit-set = "0.5"
smallvec = "0.6.1"

[target.'cfg(feature="serde")'.dependencies]
cgmath = { version = "0.16", features = ["serde", "mint"] }
num = { version = "0.2", features = ["serde"] }

[dev-dependencies]
genmesh = "0.5"

